// <auto-generated />
using System;
using API_BANCO.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_BANCO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251031023130_newmigration")]
    partial class newmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_BANCO.Models.Entities.AmortizacionCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CapitalPagado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CreditoBancoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InteresPagado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoPendiente")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorCuota")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreditoBancoId");

                    b.ToTable("AmortizacionesCredito");
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.ClienteBanco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TieneCreditoActivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ClientesBanco");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "0101010101",
                            EstadoCivil = "Soltero",
                            FechaNacimiento = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Juan Pérez",
                            TieneCreditoActivo = false
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "0202020202",
                            EstadoCivil = "Casado",
                            FechaNacimiento = new DateTime(1985, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "María García",
                            TieneCreditoActivo = false
                        },
                        new
                        {
                            Id = 3,
                            Cedula = "0303030303",
                            EstadoCivil = "Soltero",
                            FechaNacimiento = new DateTime(1995, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Carlos López",
                            TieneCreditoActivo = false
                        },
                        new
                        {
                            Id = 4,
                            Cedula = "0404040404",
                            EstadoCivil = "Casado",
                            FechaNacimiento = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Ana Torres",
                            TieneCreditoActivo = false
                        },
                        new
                        {
                            Id = 5,
                            Cedula = "0505050505",
                            EstadoCivil = "Soltero",
                            FechaNacimiento = new DateTime(1988, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Luis Castillo",
                            TieneCreditoActivo = false
                        });
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.CreditoBanco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteBancoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoAprobado")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("NumeroCuotas")
                        .HasColumnType("int");

                    b.Property<decimal>("TasaInteres")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteBancoId");

                    b.ToTable("CreditosBanco");
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteBancoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TipoCuenta")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteBancoId");

                    b.ToTable("Cuentas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteBancoId = 1,
                            NumeroCuenta = "1234567890",
                            Saldo = 1800.00m,
                            TipoCuenta = 1
                        },
                        new
                        {
                            Id = 2,
                            ClienteBancoId = 2,
                            NumeroCuenta = "9876543210",
                            Saldo = 2400.00m,
                            TipoCuenta = 1
                        },
                        new
                        {
                            Id = 3,
                            ClienteBancoId = 3,
                            NumeroCuenta = "5556667771",
                            Saldo = 900.00m,
                            TipoCuenta = 2
                        },
                        new
                        {
                            Id = 4,
                            ClienteBancoId = 4,
                            NumeroCuenta = "5556667772",
                            Saldo = 3200.00m,
                            TipoCuenta = 1
                        },
                        new
                        {
                            Id = 5,
                            ClienteBancoId = 5,
                            NumeroCuenta = "5556667773",
                            Saldo = 1500.00m,
                            TipoCuenta = 1
                        });
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.ToTable("Movimientos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 6, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7457),
                            Monto = 700.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 2,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 21, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7463),
                            Monto = 300.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 3,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 22, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7465),
                            Monto = 150.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 4,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 11, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7467),
                            Monto = 500.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 5,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 24, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7468),
                            Monto = 200.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 6,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 16, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7470),
                            Monto = 650.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 7,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 26, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7471),
                            Monto = 220.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 8,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 28, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7473),
                            Monto = 120.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 9,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 29, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7474),
                            Monto = 400.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 10,
                            CuentaId = 1,
                            Fecha = new DateTime(2025, 10, 30, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7476),
                            Monto = 80.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 11,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 16, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7477),
                            Monto = 1200.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 12,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 26, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7479),
                            Monto = 400.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 13,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 3, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7480),
                            Monto = 300.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 14,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 9, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7482),
                            Monto = 450.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 15,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 13, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7483),
                            Monto = 200.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 16,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 19, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7485),
                            Monto = 600.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 17,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 23, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7486),
                            Monto = 90.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 18,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 25, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7488),
                            Monto = 720.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 19,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 27, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7489),
                            Monto = 50.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 20,
                            CuentaId = 2,
                            Fecha = new DateTime(2025, 10, 30, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7490),
                            Monto = 510.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 21,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 1, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7492),
                            Monto = 250.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 22,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 4, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7493),
                            Monto = 60.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 23,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 7, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7495),
                            Monto = 140.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 24,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 10, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7496),
                            Monto = 310.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 25,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 12, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7498),
                            Monto = 80.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 26,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 15, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7500),
                            Monto = 500.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 27,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 17, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7501),
                            Monto = 40.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 28,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 20, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7503),
                            Monto = 280.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 29,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 22, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7504),
                            Monto = 55.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 30,
                            CuentaId = 3,
                            Fecha = new DateTime(2025, 10, 28, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7506),
                            Monto = 360.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 31,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 1, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7507),
                            Monto = 900.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 32,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 6, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7508),
                            Monto = 1100.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 33,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 8, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7510),
                            Monto = 300.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 34,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 10, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7511),
                            Monto = 750.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 35,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 13, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7513),
                            Monto = 200.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 36,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 16, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7514),
                            Monto = 600.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 37,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 21, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7516),
                            Monto = 500.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 38,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 24, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7517),
                            Monto = 150.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 39,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 27, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7518),
                            Monto = 820.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 40,
                            CuentaId = 4,
                            Fecha = new DateTime(2025, 10, 29, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7520),
                            Monto = 100.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 41,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 2, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7521),
                            Monto = 500.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 42,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 5, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7523),
                            Monto = 300.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 43,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 9, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7524),
                            Monto = 120.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 44,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 11, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7525),
                            Monto = 450.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 45,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 14, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7527),
                            Monto = 200.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 46,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 18, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7528),
                            Monto = 90.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 47,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 22, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7530),
                            Monto = 380.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 48,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 25, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7531),
                            Monto = 70.00m,
                            Tipo = "Retiro"
                        },
                        new
                        {
                            Id = 49,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 28, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7532),
                            Monto = 600.00m,
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 50,
                            CuentaId = 5,
                            Fecha = new DateTime(2025, 10, 30, 2, 31, 29, 779, DateTimeKind.Utc).AddTicks(7534),
                            Monto = 250.00m,
                            Tipo = "Deposito"
                        });
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasena = "MONSTER1",
                            Nombre = "MONSTER"
                        });
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.AmortizacionCredito", b =>
                {
                    b.HasOne("API_BANCO.Models.Entities.CreditoBanco", "CreditoBanco")
                        .WithMany("Amortizaciones")
                        .HasForeignKey("CreditoBancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditoBanco");
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.CreditoBanco", b =>
                {
                    b.HasOne("API_BANCO.Models.Entities.ClienteBanco", "ClienteBanco")
                        .WithMany()
                        .HasForeignKey("ClienteBancoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteBanco");
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.Cuenta", b =>
                {
                    b.HasOne("API_BANCO.Models.Entities.ClienteBanco", "ClienteBanco")
                        .WithMany()
                        .HasForeignKey("ClienteBancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteBanco");
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.Movimiento", b =>
                {
                    b.HasOne("API_BANCO.Models.Entities.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("API_BANCO.Models.Entities.CreditoBanco", b =>
                {
                    b.Navigation("Amortizaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
